### ISSUE TITLE
t/11-gas.t fails with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [stphnlyd/perl5-Math-LOESS#1]
If perl was compiled with increased floating point accuracy (i.e. with -Duselongdouble), then the test suite fails. See http://www.cpantesters.org/cpan/report/f54aa26c-7b31-11e9-b670-c0bb88b65f0a for a sample fail report.

**Comment by iynehz** [comment]
Thanks. I just uploaded a new trail release. Let's see if it can fix the issue.

**Comment by iynehz** [comment]
Fix confirmed http://matrix.cpantesters.org/?dist=Math-LOESS+0.0000_02
